// Class automatically generated by	Dev-C++	New	Class wizard
#ifndef	AUTHORIZEHTTPCONNECTION_H
#define	AUTHORIZEHTTPCONNECTION_H

#include <iostream>
#include <string>
#include <cstdio>
#include <vector>
#include <pthread.h>


#include "httpconnection.h"	// inheriting class's header file

/*
 * No description
 */
class AuthorizeHTTPConnection :	public HTTPConnection{
	public:
		// class constructor
		AuthorizeHTTPConnection(class RoomMember *oNewMember,class Server *oNewServer);
		// class destructor
		~AuthorizeHTTPConnection();

		bool authorize();
		bool sendAuthorization();

		RoomMember *oMember;
		class Server *oServer;
		bool bRemoved;
		bool bFinished;
		bool bDelete;

		bool bResultAuthorized;
		std::string sServerXML;

		std::string	sPOSTBuffer;

};

#endif // AUTHORIZEHTTPCONNECTION_H
