// Class automatically generated by Dev-C++ New Class wizard

#ifndef ROOMMEMBER_H
#define ROOMMEMBER_H

#include <iostream>
#include <string>
#include <cstdio>
#include <vector>
#include <stdio.h>



class RoomMember{

	public:
		// class constructor
		RoomMember(class Room *oNewRoom,class User *oNewUser,string *sNewAuthorizeXML);
		// class destructor
		~RoomMember();

		bool sendMessage(class Message *oMessage);
		bool authorized();
        void reject();

		
    public:
        class AuthorizeHTTPConnection *oAuthorization;
        bool bAuthorizationOpen;

        std::string sServerXML;
        std::string sUserXML;
        std::string sAuthorizeXML;
        
        class Room *oRoom;
        class User *oUser;
        bool bAuthorized;
        bool bDelete;

};

#endif // ROOMMEMBER_H
